language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements-tests.txt
script:
  - py.test --cov=syslog_rfc5424_formatter --cov-report=term-missing --cov-fail-under=90 -v tests/
